### PR TITLE
Add server nickname to AliasAuthor

### PR DESCRIPTION
**Pull request by ianfhunter**
### Summary

- Adds server nickname to AliasAuthor so it can be accessed by aliases.
- Adds some documentation to clarify the different types of names

I think maybe Display Name and Server Nickname were confused before. Here is how they are, maybe the intention of some display_name usages are to use the server nickname.

Example:
image
image

Name: "boopyboop."
Display Name: "Boop"
Guild Nickname: "Boop (DM) GMT+0"

### Changelog Entry
Server nicknames are now accessible within Avrae

#### PR Type

- [x] This PR is a code change that implements a feature request.
- [ ] This PR fixes an issue.
- [x] This PR adds a new feature that is not an open feature request.
- [ ] This PR is not a code change (e.g. documentation, README, ...)
#### Other
- [ ] This PR is a breaking change (e.g. methods or parameters removed/renamed)
- [x] If code changes were made then they have been tested.
- [x] I have updated the documentation to reflect the changes.

### CODE REVIEW

**Comment by ianfhunter** [comment]
The files that fail on lint have nothing to do with my code, but i guess ill fix them

**Comment by SeanStoves** [comment]
> The files that fail on lint have nothing to do with my code, but i guess ill fix them

Sync w/ the nightly branch, and the files are fixed :)

**Comment by ianfhunter** [comment]
oh :)

**Comment by ianfhunter** [comment]
Closing while I reframe the problem

**Pull request closed without merging**
