### PR TITLE
Update dice.py for AVR-944

### PR DESCRIPTION
**Pull request by TheReverendB**
rstrip backslashes from `!roll` VerboseMDStringifier

### Summary
Here goes a short summary about what the PR is about.

### Changelog Entry
Here goes a short one line about the PR to display in the Changelog ( optional )

#### PR Type

- [ ] This PR is a code change that implements a feature request.
- [x] This PR fixes an issue.
- [ ] This PR adds a new feature that is not an open feature request.
- [ ] This PR is not a code change (e.g. documentation, README, ...)
#### Other
- [ ] This PR is a breaking change (e.g. methods or parameters removed/renamed)
- [ ] If code changes were made then they have been tested.
- [ ] I have updated the documentation to reflect the changes.

### CODE REVIEW

**Comment by SeanStoves** [comment]
@TheReverendB I see it failing in a github test.  Was this tested , or do we need to test it still ?

**Comment by TheReverendB** [comment]
My local is currently not working.

Tested in Python only for the # of escapes

**Comment by SeanStoves** [comment]
> My local is currently not working.
> 
> Tested in Python only for the # of escapes

Aight, we will test the code, and if it needs anything, we will clean it up :) @kevklash or @tiberius0954 if you can run the tests and test the code locally :)

**Comment by TheReverendB** [comment]
@SeanStoves I think it's because you can't have `\` in an f-string (though I thought we updated to the version of Python where you could)

**Pull request merged**
