### PR TITLE
adding <, > and == for the aliasskill

### LINKED ISSUE #1500: AFR-787 Add support for the comparison operators (`>`, `<`, `==`, etc) to `AliasSkill`,  to compare with it's `AliasSkill.value`
**Feature Request:** Add support for the comparison operators (`>`, `<`, `==`, etc) to `AliasSkill`,  to compare with it's `AliasSkill.value`
**Who would use it?** Comparing the values of a skill while still keeping the skill object intact, such as with `min` and `max`
**What part of the bot?** Aliasing
**How would it work?** The comparison operators would compare the `AliasSkill.value` to `other`
**Why should this be added?** If you're making something that has a choice of skills and want to take the higher of the 2 options, a pythonic way would be to use `max(AliasSkill, AliasSkill)`, however this does not work due to the lack of comparison support. Furthermore, the addition of comparison support would allow for sorting lists including an `AliasSkill` object

- Infinidoge#1337

> Upvote - R to the Ichie#6193

> Upvote - Dr Turtle#1771

> Upvote - spamandtuna#9657

> Upvote - Riptidecord#7191

> Upvote - Infinidoge#1337

> Upvote - Mobius#1442

> Upvote - bobschnitzenheimer#2159

> Upvote - merien#7290

Votes: +8 / -0

### PR DESCRIPTION
**Pull request by driesceuppens**
### Summary
Resolves #1500 
Adding support for the <, > and == operators in the aliasskill class.

#### PR Type

- [x] This PR is a code change that implements a feature request.
- [ ] This PR fixes an issue.
- [ ] This PR adds a new feature that is not an open feature request.
- [ ] This PR is not a code change (e.g. documentation, README, ...)
#### Other
- [ ] This PR is a breaking change (e.g. methods or parameters removed/renamed)
- [ ] If code changes were made then they have been tested.
- [ ] I have updated the documentation to reflect the changes.

### CODE REVIEW

**Comment by driesceuppens** [comment]
I just noticed Dr. Turtle's comment, Might as well add those. Sorry for being clumsy 😄

**Comment by zhudotexe** [comment]
Also technically, the presence of `__gt__` is not necessary (Python implicitly handles when the operation is only defined for one operand):
```py
class A:
    def __init__(self, v):
        self.v = v
    def __lt__(self, other):
        return isinstance(other, A) and self.v < other.v
    def __eq__(self, other):
        return isinstance(other, A) and self.v == other.v
    
one = A(1)
two = A(2)
one < two
# True
one > two
# False
one == two
# False
one <= two
# Traceback (most recent call last):
#   File "<input>", line 1, in <module>
# TypeError: '<=' not supported between instances of 'A' and 'A'
```

(Also, you can add more commits to the branch instead of closing and reopening the PR)

**Comment by Infinidoge** [comment]
If you define the greater than, it no longer needs the `isinstance` check though, since it acts as the inverse operator.

```py
class A:
    def __init__(self, value):
        self.value = value

    def __lt__(self, other):
        return self.value < other

    def __gt__(self, other):
        return self.value > other


class B:
    def __init__(self, value):
        self.value = value

    def __lt__(self, other):
        return self.value < other

A1 = A(1)
A2 = A(2)

B1 = B(1)
B2 = B(2)

try:
    assert A1 < A2
except TypeError:
    print("A1 < A2: doesn't work")
else:
    print("A1 < A2: works")

try:
    assert B1 < B2
except TypeError:
    print("B1 < B2: doesn't work")
else:
    print("B1 < B2: works")
```
Results in:
```
A1 < A2: works
B1 < B2: doesn't work
```

**Comment by Infinidoge** [comment]
(Additionally, this allows for proper comparison with other types that can compare ints)

**Comment by driesceuppens** [comment]
So what would be better, adding all 5 or having the isinstance checks?

**Comment by zhudotexe** [comment]
Doge just showed me https://rszalski.github.io/magicmethods/#comparisons - it looks like maybe `__cmp__` is the best choice

**Comment by zhudotexe** [comment]
I lied, it was removed in Python 3

**Pull request merged**
