### PR TITLE
Add slash command check

### PR DESCRIPTION
**Pull request by storytellermahkasad**
### Summary
Adds Discord Slash-command conflict checking to prevent Avrae from becoming non-responsive to a prefix.

#### PR Type

- [ ] This PR is a code change that implements a feature request.
- [ ] This PR fixes an issue.
- [X] This PR adds a new feature that is not an open feature request.
- [ ] This PR is not a code change (e.g. documentation, README, ...)
#### Other
- [ ] This PR is a breaking change (e.g. methods or parameters removed/renamed)
- [X] If code changes were made then they have been tested.
- [X] I have updated the documentation to reflect the changes.

### CODE REVIEW

**Review by zhudotexe — COMMENTED** [review]
imo, this should be a warning + confirm rather than a hard restriction for if some user wants to do it anyway

**Comment by storytellermahkasad** [comment]
> imo, this should be a warning + confirm rather than a hard restriction for if some user wants to do it anyway

My testing of it, though brief, showed Avrae stopped responding entirely as soon as I had any prefix that began with a slash.

**Comment by zhudotexe** [comment]
Weird, I can't repro that, it seems to work with `/` just fine (Discord does complain the first time you try and send it on the desktop client, but mobile clients have no such issue)

**Comment by storytellermahkasad** [comment]
Same now, will adjust to warning and confirm. Not sure what was going on at the time :\ I blame Discord.

**Review by zhudotexe — APPROVED** [review]

**Pull request merged**
