### PR TITLE
Adds a `set_gvar(name,value)` to scripting.

### PR DESCRIPTION
**Pull request by Croebh**
Returns `None` if not found, `True` if edited, and `False` if no editor permission

### CODE REVIEW

**Comment by mommothazaz123** [comment]
I intentionally didn't include a set_gvar in scripting - gvars are intended to be a static data type

**Comment by lyrakat** [comment]
What are the odds this could be revisited? GVARs allow a few things that other variable types don't, including a shared store of persistent data. Allowing them to be created and modified in scripting could dramatically increase the power of a variety of custom aliases, especially those used for things like custom resource tracking etc on discord D&D communities

**Comment by Croebh** [comment]
I personally would love to see this implemented. The bot, game, community and types of data stored in gvars has changed a lot in the (Gods, seven??) years since this was closed.

@danielmcknightWZ @zacharycohn

**Comment by 1drturtle** [comment]
+1

**Comment by 7he4lph4** [comment]
This could mean that aliases can now collect analytics on how they're used, and several other use cases. Very cool.

**Comment by danielmcknightWZ** [comment]
> I personally would love to see this implemented. The bot, game, community and types of data stored in gvars has changed a lot in the (Gods, seven??) years since this was closed.
> 
> @danielmcknightWZ @zacharycohn

We'll toss it back in the hopper for review!

**Comment by lyrakat** [comment]
Awesome! Glad to hear that!
If this does get added it'd probably need to be a little more involved, since gvars use UUIDs instead of names. Probably a create_gvar that returns the new UUID, and the ability to edit the editors list somehow would be required to match the !gvar command's functionality

**Pull request closed without merging**
